### ISSUE TITLE
egXML not properly handled

### ISSUE THREAD

**Issue by lb42** [TEIC/CETEIcean#1]
Currently the content of egXML elements is  formatted in the same way as other elements. This is wrong, if only because it is not in the TEI namespace. What needs changing? For an example, see http://lb42.github.io/W/talk.html

**Comment by hcayless** [comment]
Should be fixed in 7f9c8b7. TEI Example-namespaced elements will get a 'teieg-' prefix.

**Comment by lb42** [comment]
How do I update my local version? I copied the new files behaviors.js and CETEI.js into my local js directory, but that didn't work. I'm guessing some magic has to be done to get a usable new CETEI.js ?

**Comment by hcayless** [comment]
If you look at the [releases](https://github.com/TEIC/CETEIcean/releases), we attach a compiled distribution that will run in most browsers. Otherwise, you'll need to get NPM working and compile from source.

**Comment by lb42** [comment]
And in any case, the egXML in the test file doesn't work either.
