### ISSUE TITLE
end-tags improperly processed

### ISSUE THREAD

**Issue by lb42** [TEIC/CETEIcean#10]
If you have an egXML containing an end-tag on a line on its own, this godforsaken lame pig of a processor loses its starting slash, thus rendering your example incomprehensible. For example:

```
<egXML xmlns="http://www.tei-c.,org/ns/1.0">
  </getWithTheProgramGuys>
</egXML>
```

gets rendered as

```
  <getWithTheProgramGuys>
```

**Comment by lb42** [comment]
This appears to have been fixed in the version of CETEICEAN used for documents in teic.github.io/TCW ... and replaced by a new bug: the appearance of a spurious data-teiname attribute (in Firefox, though not mysteriously in Chrome)

**Comment by lb42** [comment]
Dunno if this is the same thing, but why oh why does this
~~~~
 <egXML xmlns="http://www.tei-c.org/ns/Examples"><content>
                              <choice xmlns="http://relaxng.org/ns/structure/1.0">
                                 <data type="float">
                                    <param name="minExclusive">0.0</param>
                                    <param name="maxExclusive">1.0</param>
                                 </data>
                                 <value>regular</value>
                                 <value>irregular</value>
                                 <value>unknown</value>
                              </choice>
                           </content></egXML>
~~~~
get rendered like this:
~~~~
<content>
                              <choice xmlns="http://relaxng.org/ns/structure/1.0">
                                 <data type="float">
                                    <param name="minExclusive"/>0.0
                                    <param name="maxExclusive"/>1.0
                                 </data>
                                 <value>regular</value>
                                 <value>irregular</value>
                                 <value>unknown</value>
                              </choice>
                           </content>
~~~~
Note the unwanted additional space after the opening &lt;content> tag  as well as the syntactically invalid representation of the &lt;param> elements.

**Comment by jamescummings** [comment]
To answer @lb42 since I've seen this in the stylesheets handling of whitespace it is because the content element is right at the start of the egXML, whereas the choice element is massively indented.  I've usually solved this kind of thing by starting the child of the egXML (e.g. 'content' in this example) on a new line not indented at all, flush to the left margin and then the other elements barely indented  from that.  I suspect that in both cases it is treating egXML content as pre-formatted blocks.   I'm not saying this is what *should* happen, just the workaround I've used when encountering this in non-CETEIcean places in the past.

**Comment by lb42** [comment]
@jamescummings this may well be the case but it doesnt explain why the &lt;param> elements get rendered so badly -- introducing an invalidity in the output whicjh wasnt there in the input

**Comment by jamescummings** [comment]
@lb42 Ah... I hadn't noticed that.  Yes. That is just wrong. :-(

**Comment by hcayless** [comment]
It is indeed wrong, but also not what I'm getting...possible you're using an older version before the serialization bugs were fixed?

fwiw I get:
````xml
<content>
    <choice xmlns="http://relaxng.org/ns/structure/1.0">
       <data type="float">
          <param name="minExclusive">0.0</param>
          <param name="maxExclusive">1.0</param>
       </data>
       <value>regular</value>
       <value>irregular</value>
       <value>unknown</value>
    </choice>
</content>
````
in both Chrome and Firefox (after reformatting the content of egXML). It is, as @jamescummings notes, not attempting to do anything to reformat egXML on its own. Possibly it should, but it will mean writing a smarter serializer.

**Comment by lb42** [comment]
I am using the version on the GitHub.io site so far as I know

**Comment by hcayless** [comment]
I think this has been fixed for a while.
