### ISSUE TITLE
Fixable browser incompatibility

### ISSUE THREAD

**Issue by lb42** [TEIC/CETEIcean#13]
On 05/01/17 08:49, Andreas Wagner wrote (on TEI-L)
> Dear David, dear list,
>
> Am 05.01.2017 um 08:13 schrieb David Maus:
>> ,----
>> | TypeError: strings[0].includes is not a function
>> | if (strings[0].includes("<")) {
>> | ---^
>> | 
>> | CETEI.js (Line 742, Column 16)
>> `----
>>
>> using GNU IceCat 38.8.0
>> Build identifier: Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0
>>
>> This "super cool CETEICEAN thingy" looks like a tremendous step
>> backwards in accessability and usability to me.
>
> As of [1], String.prototype.includes is one of the few ES6 string functions
> that the Firefox 38 engine did not yet support. However, Ff 38 is obsolete for
> more than a year now, and newer firefox releases support the function
> (Extended Support Release 45 was in March 2016).
> Yet GNU Icecat seems to have moved to 45 only in Dec 2016, and on Windows and
> Mac it is still on 38.8.0 [2]. Since you are on windows, I guess you are out
> of luck for the moment.
>
> You could bug the IceCat maintainers to hurry with their windows release, or
> maybe you (or even CETEICEAN upstream) could use indexOf() instead of
> includes() according to [3].
>
> [1] http://kangax.github.io/compat-table/es6/
> [2] https://en.wikipedia.org/wiki/GNU_IceCat#Releases
> [3]
> http://stackoverflow.com/questions/31340868/includes-not-working-in-all-browsers
>
> HTH,
> Andreas
>
>
>

**Comment by hcayless** [comment]
I'm open to the idea of building in polyfills for newer functions used by CETEIcean, and I'm even open to the idea of building versions that support older browsers like IE eventually. But this complaint is based on an old version of a browser that is no longer supported on the Windows platform, so I'm not inclined to support it.
