### ISSUE TITLE
Readme.md and CSS

### ISSUE THREAD

**Issue by Dominique-M** [TEIC/CETEIcean#14]
By “just by grabbing the CETEI.js” I got one long line with all contents, until I understood that I had to also grab CETEIcean.css “and linking to it … like the examples do”. None of the usual CSS I use with TEI stylesheets was of any help. Of course it goes without saying… now that I think of it, I feel stupid, but it took me some time. I suggest to expand that sentence in the Readme with something about the CSS.

**Comment by hcayless** [comment]
That's a good suggestion. Thanks! Writing documentation is hard :-)
