### ISSUE TITLE
Error on files with xml version 1.1

### ISSUE THREAD

**Issue by Necklaces** [TEIC/CETEIcean#18]
A file with 

```
<?xml version="1.1" encoding="UTF-8"?>
```
In the start of the file

Returns:

> XML Parsing Error: XML declaration not well-formed
> Location: http://localhost:8000/
> Line Number 1, Column 16:
>
> \<?xml version="1.1" encoding="UTF-8"?\>
> ---------------^

Literally changing the line to:

```
<?xml version="1.0" encoding="UTF-8"?>
```

Fixes the issue..

**Comment by lb42** [comment]
See https://stackoverflow.com/questions/4508283/xml-version-1-1-not-accepted-by-browsers

Sent from my Huawei Mobile

-------- Original Message --------
Subject: [TEIC/CETEIcean] Error on files with xml version 1.1 (#18)
From: Nichlas Severinsen
To: TEIC/CETEIcean
CC: Subscribed


A file with

<?xml version="1.1" encoding="UTF-8"?>


In the start of the file

Returns:

XML Parsing Error: XML declaration not well-formed
Location: http://localhost:8000/
Line Number 1, Column 16:

<?xml version="1.1" encoding="UTF-8"?>
---------------^

Literally changing the line to:

<?xml version="1.0" encoding="UTF-8"?>


Fixes the issue..

**Comment by hcayless** [comment]
Since this is dependent on the browser's built-in XML parser, there's probably nothing we can do about it.
