### ISSUE TITLE
Styling of links

### ISSUE THREAD

**Issue by martindholmes** [TEIC/CETEIcean#2]
Lovely work, this! I'm really glad to see it.

The example pages show that when a TEI `<ptr>` is used, the resulting link looks like a link (underline and cursor: pointer), but for `<ref>`s this doesn't happen (in Firefox, at any rate). I think this is because the JS is setting the `@href` attribute in the case of `<ptr>` but not for `<ref>`. You might jsut be able to add this at line 88/89:

`content.setAttribute("href", elt.getAttribute("target"));`

**Comment by hcayless** [comment]
Thanks Martin! This is mostly the CSS. In the example, ptr is implemented by putting an HTML link inside it, but ref just has an event handler and some CSS styling. We'll try to get them better aligned.

**Comment by hcayless** [comment]
This is long-fixed.
