### ISSUE TITLE
Support for JS-frameworks (Vue, React etc.)

### ISSUE THREAD

**Issue by arjanski** [TEIC/CETEIcean#27]
Dear CETEIcean team,

First of all: Hats off and congratulations to this exciting little library! Very promising approach that could be a game changer for some projects I know.

### Problem
I have tried using CETEIcean in a modern JS framework such as Vue.js which uses a ShadowDOM. Rendering your TEI test file throws errors regarding the window object. I assume this has to do with how Vue treats the DOM. 

### Goal
I would like to be able to receive HTML5 from CETEIcean to further process using Vue.js, eventually rendering it in a template.

Do you have any experience using CETEIcean in such environments, or could provide any tips? Any help would be greatly appreciated.

Best wishes

**Comment by hcayless** [comment]
@arjanski Thanks! Making it compatible with Virtual DOM implementations is something I've been wanting to work on. Can you share with us what your example code that isn't working so I can have a shot at fixing what's not working in CETEIcean?

**Comment by arjanski** [comment]
@hcayless Thank you for the swift reply, sounds great!

I tried using it in a Nuxt (https://nuxtjs.org/) application first, but will provide you with a "vanilla" Vue boilerplate git repo asap. This way you could run it locally and see the behavior yourself. Sounds good?

I am open to assist you in any form I can, as this would mean a lot to our current DH workflow.

P.S.: 
This is how I'd envision a Vue single-file component rendering TEI being served by CETEIcean:

- In `created()` lifecycle hook, trigger CETEIcean's `getHTML5` method to fetch and transform TEI
(cf. https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram)
- The easiest would be to receive a HTML string
- This string would be rendered either a) via Vue's `v-html` directive (https://vuejs.org/v2/api/#v-html) or b) as part of a render function (https://vuejs.org/v2/guide/render-function.html)

This would open huge possibilities IMHO, e.g. adding dynamic UI elements such as tooltips/modals by  injecting Vue markup into the HTML.

**Comment by arjanski** [comment]
Here's a bare-bones Vue project containing the library if you want to have a look:

https://github.com/arjanski/ceteicean-test

After NPM install you can fire up the dev server and can look around. It's basically just one page trying to render the sample TEI you provide in the repo. If you haven't used Vue yet, it might be helpful to install the Vue Devtools (FF, Chrome) for additional debugging infos.

Don't know if you are familiar with Vue, so here's a short walkthrough:
- /views/TEI.vue holds the Vue component that should use CETEIcean to render the XML.
- /ceteicean holds the library

Using the sample from the docs and trying to console.log the data, I am getting a parsererror in the console. Not sure though if I have done everything right there. 

If you have any further questions let me know, I'll be happy to assist as much as I can!

**Comment by arjanski** [comment]
FYI, this is the error that gets thrown in a Nuxt application:

![Screenshot from 2020-02-14 12-14-33](https://user-images.githubusercontent.com/13831998/74526453-b9549800-4f23-11ea-8e12-e8d2c29ac98d.png)

**Comment by hcayless** [comment]
I can make your minimal version work with a few tweaks. See https://gist.github.com/hcayless/34e13eecc7686aeafd1f37592730ec5e

I don't think this suffers from the same issues as your Nuxt app, it just wasn't able to load the TEI file. Note that I still may have done things wrong here in my ignorance of Vue's conventions :-).

I'm going to try pushing a couple of changes that will allow CETEIcean to run in the absence of a `window` object, which seems to be where it's blowing up. Maybe that will fix your issue? Or at least reveal the next bug.

**Comment by arjanski** [comment]
Wow that's fantastic, thanks a lot!

I feel bad not seeing this, but even happier that it's working.

I'll also put together a small Nuxt application that will run in server-side rendering mode, in case you want to take this further.

Thanks again for this, made my day.

**Comment by arjanski** [comment]
Dear @hcayless, sorry for my absence due to family-related matters.

I found the time to set up a bare-bones Nuxt project with CETEIcean for testing purposes. As stated before, the error here is different than in a traditional Vue.js app ("window not defined"). 

I assume this has to do with server-side rendering mode of Nuxt, but basically have no real clue.

If interested, you can find the repo here:
https://github.com/arjanski/ceteicean-test-nuxt

After the usual `yarn install` (node_modules should be sufficient as is though), have a look at /pages/index.vue. This mimics the test component from the Vue app you successfully debugged. 

Thank you very much in advance for any thoughts / recommendations.

If CETEIcean could be used with Nuxt, I already have a concrete project in mind where this would be extremely valuable.

**Comment by hcayless** [comment]
Thanks for this @arjanski! I'll let you know what I find out.

**Comment by raffazizzi** [comment]
Hi there, just to add another perspective, I've used CETEIcean with React often. I follow two approaches:

1. I rely on DOM operations after rendering. E.g. with `useRef()` and `useEffect()`
See full example here: https://github.com/raffazizzi/simple-ceteicean-react

```jsx
import React, {useRef, useEffect} from 'react';
import './App.css';
import CETEI from 'CETEIcean';

function App() {
  const teiDiv = useRef(null);

  useEffect(() => {
    async function getTEI() {
      const ct = new CETEI();
      
      // Override default CETEI TEI behaviors.
      ct.addBehavior('tei', 'teiHeader', undefined);
  
      const teiData = await ct.getHTML5(`example.xml`);
  
      // Add here other DOM operations as needed.
      teiDiv.current.innerHTML = teiData.outerHTML;
    }
    getTEI();
  })
  
  return (
    <div className="App">
      <div ref={teiDiv}>Loading...</div>
    </div>
  );
}

export default App;
```

2. Treat each TEI element as a React element object for maximum integration with the React ecosystem. This approach might help with other frameworks, too. 
Briefly:
a. Get data and use CETEIcean asynchronously as above
b. Pass it to a dedicated TEIElement React component, e.g. `<TeiElement teiDomElement={teiDomData} />`
c. TEIElement loops through children and instantiates itself again when elements are met (returning text nodes right away, etc.)
```jsx
const teiChildren = Array.from(props.teiDomElement.childNodes).map((teiEl, i) => { 
  switch (teiEl.nodeType) {
    case 1:
      return <TeiElement teiDomElement={teiEl} />;
    case 3:
      return teiEl.nodeValue;
    default:
      return null;
  }        
})
```
If you need to do something special with a given element, you can catch it here and send it to a dedicated component, and more.
For a full example, check out this work-in-progress project where I use this approach: https://github.com/raffazizzi/mermtt/

**Comment by arjanski** [comment]
Nice, very helpful @raffazizzi! This is exactly what my next move would be (even though in Vue this might be a bit less straightforward unfortunately). 

The more I look at it, CETEIcean seems really sleek and such a time-saver. I don't understand why it's not used more in DH. At least in Germany it's not (yet).

**Comment by StephanMa** [comment]
It’s easy... TEI is XML. That’s why it has to be some XQuery/Xpath magic ... sadly

**Comment by arjanski** [comment]
Short update from my end trying to get the library running in Nuxt.js:

The `window undefined` bug is due to server-side rendering features of Nuxt, as predicted:
https://nuxtjs.org/faq/window-document-undefined

One needs to specifically tell Nuxt not to use the library on the server side:
```
if (process.client) {
  require('../ceteicean/CETEI.js')
}
```
This way, the bug is gone and the library seemingly intends to do its job to fetch an XML. However, I now get a "Could not get XML file" in the logs when trying to load a local XML file.

```
  mounted() {
    var CETEIcean = new CETEI()
    var self = this
    CETEIcean.getHTML5('testTEI.xml', function(data) {
      self.TEI = data.outerHTML
    })
  }
```

P.S.: An alternative seems to be registering a plugin in Nuxt with a mode parameter set to `client`:  https://nuxtjs.org/guide/plugins#client-side-only

**Comment by GrantLS** [comment]
> I can make your minimal version work with a few tweaks. See https://gist.github.com/hcayless/34e13eecc7686aeafd1f37592730ec5e
> 
> I don't think this suffers from the same issues as your Nuxt app, it just wasn't able to load the TEI file. Note that I still may have done things wrong here in my ignorance of Vue's conventions :-).
> 
> I'm going to try pushing a couple of changes that will allow CETEIcean to run in the absence of a `window` object, which seems to be where it's blowing up. Maybe that will fix your issue? Or at least reveal the next bug.

@hcayless, your example works well but it's now outdated, as it uses the Vue options API and not the composition API. Here's how I've gotten it to work (with refs rather than `this`):

```
<script setup>
import { onMounted, ref } from "vue";
import CETEI from "CETEIcean";

const props = defineProps({
  xmlString: {
    type: String,
  }
});

const display = ref(null);

onMounted(() => {
  const CETEIcean = new CETEI({ ignoreFragmentId: true });
  CETEIcean.makeHTML5(props.xmlString, (data) => {
    display.value.appendChild(data);
  });
});
</script>

<template>
  <div ref="display"></div>
</template>
```

I've got the XML as a string in a parent component, so I'm using `makeHTML5` but that's immaterial. Thanks for all your work on CETEIcean.

**Comment by raffazizzi** [comment]
Hi all, you may want to check out the latest beta version on NPM `npm install CETEIcean@1.8.0-beta.1`, which implements [this PR](https://github.com/TEIC/CETEIcean/pull/64) while we finish thoroughly reviewing it before next release.
It makes CETEIcean much easier to use in a Node JS environment by better insulating global/window calls and by letting users provide their own DOM processor (such as jsdom). This is essential to enable server side rendering and static site generation.

**Comment by arjanski** [comment]
Thank you for the notice @raffazizzi , this is fantastic news and will unlock superpowers for TEI-based projects! 👍

**Comment by raffazizzi** [comment]
Closing as this should be addressed by [v 1.8.0](https://github.com/TEIC/CETEIcean/releases/tag/v1.8.0).

**Comment by arjanski** [comment]
Thank you again, huge effort!

And btw @raffazizzi , I had the exact same idea you've started working on:

https://github.com/raffazizzi/astro-tei

Astro & CETEIcean, now that's a combo. And I don't have even have to set it up myself... 🚀 🙏

**Comment by raffazizzi** [comment]
@arjanski it's very much a work in progress, but it is what prompted these latest changes to CEITEIcean. After you take a look, let me know if you want to contribute or even work together on it!

**Comment by arjanski** [comment]
@raffazizzi  Will do. Great to also see Typescript being used. Just had a quick look at the demo - looking great. I think I might have found a small bug, will report in the repo once I'm sure. 

Let's see if I can contribute in any way.
