### ISSUE TITLE
npm run build didn't work for me.

### ISSUE THREAD

**Issue by jamescummings** [TEIC/CETEIcean#3]
:~/git/CETEIcean$ npm run build

> CETEIcean@0.0.0 build /home/jamesc/git/CETEIcean
> rollup -c rollup.config.js

/usr/bin/env: node: No such file or directory
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0

**Comment by hcayless** [comment]
I think Lou was running into the same error. A little Googling suggests
trying

apt-get install nodejs-legacy

**Comment by jamescummings** [comment]
ah, that was indeed it
