### ISSUE TITLE
CETEI.js file needs some pre-processing

### ISSUE THREAD

**Issue by lb42** [TEIC/CETEIcean#30]
The README file says "You can use CETEIcean in your projects just by grabbing the CETEI.js file from the latest release and linking to it in an HTML file"
This (to the naive reader) means I can just copy the file src/CETEI.js from the latest github release and use it from a webpage. but I think something more is needed to turn the source into something usable. 
Specifically, I needed to 
- sudo apt install npm
- npm i
- npm run build

and then copy not the version of CETEI.js in src, but the one in dist.
This is no doubt entirely obvious to the JS-experienced, but that's not entirely coterminous with the potential CETEICEAN user community!
I suggest changing the wording quoted above to something like
"You can use CETEIcean in your projects by grabbing the built version of the CETEI.js file from the latest release and linking to it in an HTML file. Build instrructions are given below."

**Comment by hcayless** [comment]
That was me being an idiot and forgetting to attach the prebuilt file to the release. Apologies. I've fixed it.
