### ISSUE TITLE
How to handle empty tei-ref elements

### ISSUE THREAD

**Issue by lb42** [TEIC/CETEIcean#31]
I have lots of `<ref>` elements whose @target I wish to process as a link. This works just fine with the default behaviour when the `<ref>` has some content, but is not so fine when the `<ref>` is empty. How should I change the existing behaviour for tei-ref so as to insert a default string?

That is, I would like
~~~~
<tei:ref target="http://wibble.com"/>
~~~~
to look like
~~~~
<a href="http://wibble.com">[string]</a>
~~~~
 where [string] is a constant I supply in the behaviour specification. For extra brownie points, this string should be concatenated with any content of the tei-ref, rather than replacing it.

**Comment by hcayless** [comment]
Something like
```js
"ref": ["<a href=\"$rw@target\">[string]</a>"]
```
should do the trick.

**Comment by lb42** [comment]
This works fine in the case where the ref is empty, but if it is not the content of the ref does not get concatenated with the string. so we get
~~~~
<a href="http://wibble.com">[string]</a> [content]
~~~~
instead of 
~~~~
<a href="http://wibble.com">[string] [content]</a>
~~~~
which doesn't look right.

**Comment by hcayless** [comment]
Ah. I was misunderstanding you. Do this:
```js
"ref": ["<a href=\"$rw@target\">[string]", "</a>"]
```
The array (what's in the `[]`) can have one or two elements, if there's one, it comes before the XML element's content. If there's two, they wrap the content.

**Comment by lb42** [comment]
Thanks. That fixes it, so I am closing this.
