### ISSUE TITLE
Strange behaviour when attribute is missing

### ISSUE THREAD

**Issue by lb42** [TEIC/CETEIcean#33]
I have a defined behaviour like this : 
`    "pb":[ "<p class='break'>[page $@n]</p>"],
 `
This make e.g. `<pb n="42"/>` look like `[page 42]` which is fine.
However, if  the n attribute is missing, it produces `[page $@n]` which seems a bit strange. Why doesn't it just do `[page ]` ?

**Comment by hcayless** [comment]
That's a bug. I just pushed a fix for it.

**Comment by lb42** [comment]
Thanks for speedy fix. I needed to rebuild (as per #30) -- is it intentional that the "dist" folder is not included in the git repo?

**Comment by hcayless** [comment]
Yeah, because it could get out of sync with the source. Probably it's just me being careful, but I like to keep the distinction: source code in the repo / build artifacts with the releases. Probably we should have our CI generate a bleeding edge version though...

**Comment by raffazizzi** [comment]
Yes, I think not including the dist folder is generally considered best practice. The npm module should include it, however, because it gets built before publishing.
