### ISSUE TITLE
Further clean-up of the CETEIcean.css

### ISSUE THREAD

**Issue by dubinsky** [TEIC/CETEIcean#34]
Comprehensive or not, `/test/CETEIcean.css` is likely to be used as a basis for styling TEI in projects that use CETEIcean. A few points that, if addressed, would make it easier, at least for me:
- add `yi` (Yiddish) to the list of the right-to-left languages;
- add `ru` (Russian) and `pl` (Polish) to the list of the left-to-right languages;
- remove space between `.5` and `em` in `tei-listbibl` rule;
- two rules for `tei-table` can be merged;
- some element names escaped recent lower-casing, e.g.: `accMat`, `addrLine`, `adminInfo`, `appInfo`, `biblFull`, `cRefPattern`, `musicNotation`, `origPlace`, `personGrp`, `secFol`, `soCalled`.

**Comment by hcayless** [comment]
These all sound pretty reasonable.

**Comment by dubinsky** [comment]
Thanks :)
