### ISSUE TITLE
Add option to mute URL fragment parsing

### ISSUE THREAD

**Issue by raffazizzi** [TEIC/CETEIcean#41]
The URL fragment parsing that is added any time `window` is available gets in the way of one-page applications, throwing errors for fragments like `#/`. I don't think it should be part of the CETEIcean core in general (it makes a big assumption about how CETEIcean is to be used in the browser), but it's been there since the early days so my request would be to add an option parameter to turn it off (thus keeping it as the default behavior).

https://github.com/TEIC/CETEIcean/blob/master/src/CETEI.js#L511

**Comment by pfefferniels** [comment]
I'm not sure if there's anything planned on it, but I'd like to mention that I often need to work around this particular problem @raffazizzi mentioned – so I strongly support this request ... :)

**Comment by raffazizzi** [comment]
I think this was added in the end: https://github.com/TEIC/CETEIcean/blob/master/src/CETEI.js#L48

So you should be able to turn it off by setting `ignoreFragmentId` to `true`:

```js
new CETEI({
  ignoreFragmentId: true
})
```

I'll add an example to the README.

**Comment by pfefferniels** [comment]
Oh great, I didn't realize – thanks!
