### ISSUE TITLE
CETEIcean does not follow <xi:include/> entries

### ISSUE THREAD

**Issue by nivaca** [TEIC/CETEIcean#48]
I have a main TEI document containing several <xi:include /> entries such as:

```xml
...
<text xml:lang="es">
  <body>
    <xi:include href="abbr.xml" xmlns:xi="http://www.w3.org/2001/XInclude" xpointer="smabbr" parse="xml" />
    ...
  </body>
</text>
...
```

However, CETEIcean doesn't parse these files.
(When I directly transform the document with XSLT, everything looks fine, though.(

Is there any way of fixing this?

**Comment by raffazizzi** [comment]
Hello, there is currently no support for XInclude. Typically, I resolve the XIncludes with custom JavaScript code before passing the document to CETEIcean. This way, you can have full control of resolving URIs (e.g. CETEIcean, from the browser, may not truly be able to always know where `abbr.xml` is). It may be possible to write a custom CETEIcean behavior to support this, too.

The easiest solution, however, would be resolving XIncludes before rendering the document with CETEIcean.

**Comment by nivaca** [comment]
Hi @raffazizzi. Thanks for your reply. I agree.
