### ISSUE TITLE
Manipulating CETEIcean output elements with JS document.querySelector('tei-p[attribute='value]')

### ISSUE THREAD

**Issue by rafaelortet-cloud** [TEIC/CETEIcean#49]
Hi Ceteicean team,

First, thanks a lot for bringing this lightweight solution for bringing TEI documents closer to the DOM! It is great!

We are running an experiment to present canonical texts in Tibetan language. We successfully built a simple user interface and have generated some custom CSS to manipulate the CETEIcean output text.

Our documents are complex in structure and require auxiliary outlines to properly navigate through the different parts of the text.  So, we are trying to build some "scrollSpy" functionality using the IntersectionObserver API as to connect the actual text and its outline, each of these parsed separately into the DOM using two instances of the CETEIcean object.

The issue is that, so far, we could not find a way to manipulate the CETEIcean generated  custom elements via  document.querySelector() or document.querySelectorAll() inside our JS logic files.

Any assistance will be so appreciated!
Rafael

![B6671545-8A9D-42B6-B6B1-9FB8F1FDA2DE](https://user-images.githubusercontent.com/59250700/139394218-0089dd3d-8b8a-41a1-b422-97b23e4fc5f8.jpeg)

**Comment by raffazizzi** [comment]
Hello, the interface looks great!

It is certainly possible to use document.querySelector to get to CETEIcean elements, and the example you have in the title should be ok (minus a small typo)

```document.querySelector("tei-p[att=val]")```

If it's returning `null` or `undefined`, it's likely that those elements aren't available on `document` yet. JS is asynchronous, so depending on how you wrote the code, it may attempt to register and place TEI elements at the same time as it's trying to run `querySelector`.

Especially if you're using one of CETEIcean's built-in methods like `getHTML5()`, I would recommend wrapping that call in a Promise and only perform queries after that promise is resolved. If you're transpiling from ES6 you can also use async/await.

It's not my preference, but you can also pass a callback to `getHTML5()` that should run after it's done.

```js
getHTML5("path.xml", () => {
document.querySelector("selector")
})
```
