### ISSUE TITLE
alternate behaviors based on attribute values - example? 

### ISSUE THREAD

**Issue by emylonas** [TEIC/CETEIcean#50]
I'm trying to write a behavior for `<ref>` that does one thing if the element has a `@type="internal"` and another if it has `@type="bibl"` attribute. I'm modeling it on the `<ref>` example in CETEIcean. The documentation seems to say that I can't make a second behavior - so I am trying to add a second component to the `<ref>` behavior.

This is not working, but I'm not sure of how the js script syntax works in this case. My js abilities are so-so. In the example below, the first part [type=internal] is fine. The question is where and how to add the [type=bibl]. And I may just be writing bad javascript...

I've looked for an example to follow but was unable to find one (which doesn't mean that there it's not there.)

``
"ref": [
              ["[type=internal]", function(elt) {
                var linkNum = elt.getAttribute("target").replace(/#A-/,"");
                var linkPre = '{{ site.baseurl }}edition/plant';
                var link = document.createElement("a");
                link.innerHTML = elt.innerHTML;
                link.href = linkPre.concat(linkNum);
                return link;
              }],
              ["[type=bibl]", ["[target]", ["<a href=\"$rw@target\">","</a>"]]]
            ]

**Comment by hcayless** [comment]
I think you're almost there. I haven't tested it, but something like

```js
{
  "ref": [
  ["[type=internal]", function(elt) {
    let linkNum = elt.getAttribute("target").replace(/#A-/,"");
    let linkPre = '{{ site.baseurl }}edition/plant';
    let link = document.createElement("a");
    link.innerHTML = elt.innerHTML;
    link.href = linkPre.concat(linkNum);
    return link;
  }],
  ["[type=bibl][target]", ["<a href=\"$rw@target\">","</a>"]]
  ]
}
```
should work. Whether the `{{ site.baseurl }}` bit works may depend on when and how your templating engine processes things. The `[type=bibl][target]` is a CSS selector, and that syntax ought to work for multiple attributes.

**Comment by lb42** [comment]
I have more or less the same problem, but a lot less javascript-competence. I want to generate different values for the link components depending on the value of tei:idno/@type
Here's where I got to 
~~~~
 ceteicean.addBehaviors( {   
   "idno" : [
       ["[type=VIAF]", function(el) {
       var prefix = 'http://viaf.org/'
       var a = document.createElement("a") 
       a.setAttribute("href", prefix + el.innerHTML)
       a.innerHTML = 'VIAF code';
       return a ;   
       } ],
      ["[type=wikidata]", function(el) {
      var prefix = 'http://wikidata.org/'
      var a = document.createElement("a") 
      a.setAttribute("href", prefix + el.innerHTML)
      a.innerHTML = 'wikidata';
      return a ; } ]
   ]
   }
~~~~
but this gives me nothing. Anything obviously screwy? (Apart from the missing ) at the end)

**Comment by hcayless** [comment]
I think you need:

```js
 ceteicean.addBehaviors( {"tei": {
   "idno" : [
       ["[type=VIAF]", function(el) {
       var prefix = 'http://viaf.org/'
       var a = document.createElement("a") 
       a.setAttribute("href", prefix + el.innerHTML)
       a.innerHTML = 'VIAF code';
       return a ;   
       } ],
      ["[type=wikidata]", function(el) {
      var prefix = 'http://wikidata.org/'
      var a = document.createElement("a") 
      a.setAttribute("href", prefix + el.innerHTML)
      a.innerHTML = 'wikidata';
      return a ; } ]
   ]
   }});
```
You're missing the first TEI bit.
