### ISSUE TITLE
Babel seems to 'trip' over double semi-colon 

### ISSUE THREAD

**Issue by D-Groenewegen** [TEIC/CETEIcean#60]
https://github.com/TEIC/CETEIcean/blob/master/src/CETEI.js#L414 ends with a duplicate semi-colon. Now this would have been a harmless issue in ES6 but it is one with a potential impact on transpiled code. 

Because the version of the platform I'm working on doesn't support ES6, I used Babel to transpile everything to ES5 and added custom-elements-es5-adapter as a dependency. This works most of the time, but sometimes behaviours don't initialise, without anything logged in the browser console/inspector. When I add the debug option to `new CETEI({ ... })`, however, these incidents translate to no rendition at all and a message in the console saying `Uncaught (in promise) ReferenceError: tagName is not defined`.

Where the original has 
```
key: "tagName",
value: function tagName(e) {
if (name.includes(":"), 1) {
    return name.replace(/:/,"-").toLowerCase();;
  } else {
    return "ceteicean-" + name.toLowerCase();
  }
}
```

my transpiled code just has 

```key: "tagName",
value: function tagName(e) {
return e.includes(":"), e.replace(/:/, "-").toLowerCase();
}
```

(with no reference to `"ceteicean-"`)

Not sure if said issue with behaviours failing to get initialised is at all related, but that code doesn't look like it's functionally equivalent. 

Which is a long way of saying we might want get rid of one of the semi-colons (I don't care which :).

**Comment by raffazizzi** [comment]
That was definitely a typo, I just removed it! Will you be able to use it like this or should we think about scheduling a new release soon?

**Comment by D-Groenewegen** [comment]
Thanks, that was quick! I'm happy to use the latest dev version, so this is fine.
