### ISSUE TITLE
Leading space before URL attribute causes .rw() method to assume an empty URL 

### ISSUE THREAD

**Issue by rsimon** [TEIC/CETEIcean#67]
Hi, 

we just ran into the following issue: we had a TEI `<graphics>` element where the `url` argument had a leading space, like so:

```xml
<figure>
  <graphic url=" https://www.example.com/image.jpg" />
</figure>
```

CETEIcean converted this into an absolute URL, pointing to the base of the document. E.g. if the document were hosted at `http://www.example.com/documents/document01.xml`, the image element generated by CETEIcean would point to the URL `http://www.example.com/documents/`.

I read into the source code, and traced the source of the issue to the `.rw()` method here:
https://github.com/TEIC/CETEIcean/blob/186ff5f22407613f2d027444fbb5ef06a1a50a5b/src/utilities.js#L146

We can easily fix this on our end by configuring a custom behavior. However I was wondering what your thoughts are. Would it make sense to simply `.trim()` the URL attribute before the RegEx check? I realize that the leading space might actually be invalid markup. But perhaps it might make sense to make things more robust? 

If you think that trimming would be ok to add to the `rw()` method, I'm happy to send a PR.

**Comment by raffazizzi** [comment]
Hi @rsimon thanks for reporting this issue! Yes, using `trim()` makes sense to me as a fix, please do send a PR!

**Comment by rsimon** [comment]
Great - PR is out!
