### ISSUE TITLE
Apparently no support for <note> elements

### ISSUE THREAD

**Issue by lb42** [TEIC/CETEIcean#9]
http://teic.github.io/TCW/purifyDoc.html has a couple of things tagged &lt;note place="end"> which are supposed to be footnotes (could be rendered as popups, perhaps) : at the moment their content just appears runon in the text, which looks weird.

**Comment by lb42** [comment]
No progress on this one?

**Comment by hcayless** [comment]
With the new behaviors implementation, this kind of thing is possible and I've put in an implementation of it (ece3bc5). I'm not 100% convinced it should be in the core behaviors object, and might move it to the examples, but it works. It does make the current incarnation of the purifyDoc look a bit funny.
